### ISSUE TITLE
Support y-aligning also

### ISSUE THREAD

**Issue by studgeek** [ech2/OS-X-Display-Arrangement-Saver#3]
As described in the readme, y-aligning is not supported. This is a placeholder for adding it eventually (so I can personally track if there is movement :).

**Comment by studgeek** [comment]
I notice in the code that y setting is just commented out. Was there an issue you were running into when it wasn't commented out (trying to understand how much work fixing it would be). Thanks!
https://github.com/oscii/OS-X-Display-Arrangement-Saver/blob/master/da/main.m#L170

**Comment by ech2** [comment]
https://github.com/ech2/OS-X-Display-Arrangement-Saver/pull/4
